<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Crypt;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Static::creating(function (){
            Cache::forget('users');
        });
        Static::updating(function (){
            Cache::forget('users');
        });
        Static::deleting(function ($user){
            Cache::forget('users');
        });
    }

    /**
     * The attributes that are mass assignable
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'user_name',
        'email',
        'role_id',
        'password',
        'provider',
        'provider_id',
        'provider_token',
    ];

    public function attachRole($roleName)
    {
        $role = Role::where('name', $roleName)->firstOrFail();
        $this->role_id = $role->id;
        $this->save();
    }

    public function role(){
        return $this->belongsTo(Role::class);
    }

    public function profile()
    {
        return $this->hasOne(Profile::class,'user_id')
            ->withDefault();
    }

    public function deviceTokens(){
        return $this->hasMany(DeviceToken::class);
    }

    public function routeNotificationForFcm($driver, $notification = null)
    {
        return $this->deviceTokens()->pluck('token')->toArray();
    }

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}
